# Site settings
title: Shakeeb Mancheri
description: Mobile App Developer and Software architect
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shakeeb M
user_description: CTO and architect in Playspots App, and Lead Mobile Engineer in Buy Me a Coffee and Lead iOS Engineer in Brew.com
user_title: Mobile App developer and Software architect.
email: shakeebmancheri@gmail.com
twitter_username: shakeebhere
github_username:  shakeebM
gplus_username:  shakeebM

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
